services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # Persistent data storage
    environment:
      POSTGRES_DB: onboarding_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001  # Run the Django development server
    volumes:
      - .:/code  # Mount the current directory inside the container
    ports:
      - "8001:8001"  # Expose the Django app on port 8000
    depends_on:
      - db
    environment:
      DB_NAME: onboarding_db
      DB_USER: username
      DB_PASSWORD: password
      DB_HOST: db 
      DB_PORT: 5432 # Your processes might already be using 5432

volumes:
  postgres_data:
